name: quizeapp
description: FireBase Quize Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.6
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  url_strategy: ^0.2.0
  flutter_localizations:
    sdk: flutter

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.3
#  onesignal_flutter: ^5.0.3

  # FIREBASE PACKAGES
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.7.3
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2
  google_sign_in: ^6.1.5
  google_mobile_ads: ^3.1.0
  http: ^1.1.0
  html: ^0.15.4
  image_picker: ^1.1.0
  file_picker: ^6.0.0
  image_picker_web: ^3.1.1
  just_audio: ^0.9.37

  paginate_firestore: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  flutter_launcher_icons: any
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/splash_app_logo.png"
    background_color: "#FAFAFA"
    theme_color: "#FFfe7848"
dependency_overrides:
#  intl: ^0.18.0
#  ffi: ^2.0.1
  cloud_firestore: ^4.3.1
#  http: ^0.13.0
#  win32: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/


