name: quizapp_flutter
description: A new Flutter application.
_author: Engelbert Richelieu Tsinda <engelbertrichelieutsinda@gmail.com>
_maintainer: Engelbert Richelieu Tsinda <engelbertrichelieutsinda@gmail.com>
publish_to: 'none'
version: 1.7.2+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.6
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  flutter_vector_icons: ^2.0.0
  intl: ^0.19.0
  flutter_advanced_drawer: ^1.3.5

  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  firebase_analytics: ^10.6.3
  google_sign_in: ^6.1.6
  firebase_auth: ^4.12.1
  google_mobile_ads:
    # git:
    #   url: https://github.com/googleads/googleads-mobile-flutter
    #   ref: 356875362ddb2ac2e0056385d2729c093722fb8d
    #   path: packages/google_mobile_ads

  otp_text_field: ^1.1.3
  image_picker: ^1.0.4
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.3.0
  dots_indicator: ^3.0.0
  onesignal_flutter: ^5.0.3 
  device_info_plus: ^9.1.0
  flutter_fortune_wheel: ^1.3.0
  motion_toast: ^2.7.9
  flutter_staggered_animations: ^1.1.1
  share_plus: ^7.2.1
  wheel_spin: ^1.0.2
  country_code_picker: ^3.0.0
  shake_animation_widget: ^3.0.4
  widget_zoom: ^0.0.4
  flutter_localizations:
    sdk: flutter
  form_validator: ^2.1.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  just_audio: ^0.9.37
  banner_carousel: ^1.2.1
  flutter_carousel_widget: ^2.2.0
  video_player: ^2.8.6
  font_awesome_flutter: ^10.7.0
  cached_video_player_plus: ^2.0.0
  get: ^4.6.6
  dio: ^5.5.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_logov.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - lang/
    - shorebird.yaml
